name: Python Application Workflow

on:
  push:
    branches: [ main ]  # Запуск при пуше в ветку main
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"  # Укажите версию Python (например, 3.10)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run setup script
      run: ./st.sh  # Запуск вашего скрипта

    - name: Verify script execution
      run: |
        echo "Dependencies installed and script executed successfully"
